spring:
  application:
    name: transactions-currency-manager
  datasource:
    url: jdbc:postgresql://localhost:5433/transactions_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

external:
  fiscal:
    # Full endpoint for rates of exchange (used by CurrencyGatewayImpl)
    rates-url: "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/rates_of_exchange"

